pipeline {
  agent {
    docker {
      image 'rust:latest'
    }
  }

    stages {
        stage('Build') {
            steps {
                sh "cargo build --release"
            }
        }
        stage('Benchmark') {
            steps {
                sh "cargo bench"
            }
        }
    }
}
