pipeline {
  agent {
    docker {
      image 'rust:latest'
    }
  }
    stages {
        stage('Setup') {
            steps {
                sh "rustup component add clippy"
            }
        }
        stage('Build') {
            steps {
                sh "cargo build --release"
            }
        }
        stage('Lint') {
            steps {
                sh "cargo clippy -- -Dwarnings"
            }
        }
        stage('Test') {
            steps {
                sh "cargo test"
            }
        }
        stage('Benchmark') {
            steps {
                sh "cargo bench"
            }
        }
    }
}
